<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EPINHYDW0B79" failures="4" tests="6" name="testngTestcases.Testcase2" time="0.097" errors="0" timestamp="2024-04-21T12:02:20 IST" skipped="2">
  <testcase classname="testngTestcases.Testcase2" name="intentionallyFail" time="0.010">
    <failure message="Intentionally failed" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Intentionally failed
at org.testng.Assert.fail(Assert.java:111)
at testngTestcases.Testcase2.intentionallyFail(Testcase2.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
    <system-out>
      <![CDATA[Test has been started: intentionallyFail
Intentionally Failing Test
Test has been failed: intentionallyFail
<a href="C:\Users\Bhagya_Kudupudi\Desktop\download.png" target="_blank">screenshot</a>
<a href="C:\Users\Bhagya_Kudupudi\Desktop\download.png" target="_blank"><img src="C:\Users\Bhagya_Kudupudi\Desktop\download.png" height=200 width=200</a>]]>
    </system-out>
  </testcase> <!-- intentionallyFail -->
  <testcase classname="testngTestcases.Testcase2" name="assertTrueCond" time="0.036">
    <failure message="Title is not matching expected [google] but found [gmail]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Title is not matching expected [google] but found [gmail]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at testngTestcases.Testcase2.assertTrueCond(Testcase2.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
    <system-out>
      <![CDATA[Test has been started: assertTrueCond
Verifying titles
Test has been failed: assertTrueCond
<a href="C:\Users\Bhagya_Kudupudi\Desktop\download.png" target="_blank">screenshot</a>
<a href="C:\Users\Bhagya_Kudupudi\Desktop\download.png" target="_blank"><img src="C:\Users\Bhagya_Kudupudi\Desktop\download.png" height=200 width=200</a>]]>
    </system-out>
  </testcase> <!-- assertTrueCond -->
  <testcase classname="testngTestcases.Testcase2" name="verifyTitle" time="0.037">
    <failure message="gmail expected:&lt;google&gt; but was:&lt;Title is not matching&gt;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: gmail expected:<google> but was:<Title is not matching>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at testngTestcases.Testcase2.verifyTitle(Testcase2.java:18)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
    <system-out>
      <![CDATA[Test has been started: verifyTitle
Test has been failed: verifyTitle
<a href="C:\Users\Bhagya_Kudupudi\Desktop\download.png" target="_blank">screenshot</a>
<a href="C:\Users\Bhagya_Kudupudi\Desktop\download.png" target="_blank"><img src="C:\Users\Bhagya_Kudupudi\Desktop\download.png" height=200 width=200</a>]]>
    </system-out>
  </testcase> <!-- verifyTitle -->
  <testcase classname="testngTestcases.Testcase2" name="softAssertCond" time="0.011">
    <failure message="Title is not matching expected [google] but found [gmail]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Title is not matching expected [google] but found [gmail]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at testngTestcases.Testcase2.softAssertCond(Testcase2.java:64)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
    <system-out>
      <![CDATA[Test has been started: softAssertCond
Test has been failed: softAssertCond
<a href="C:\Users\Bhagya_Kudupudi\Desktop\download.png" target="_blank">screenshot</a>
<a href="C:\Users\Bhagya_Kudupudi\Desktop\download.png" target="_blank"><img src="C:\Users\Bhagya_Kudupudi\Desktop\download.png" height=200 width=200</a>]]>
    </system-out>
  </testcase> <!-- softAssertCond -->
  <testcase classname="testngTestcases.Testcase2" name="intentionallySkip" time="0.003">
    <skipped/>
    <system-out>
      <![CDATA[Test has been started: intentionallySkip]]>
    </system-out>
  </testcase> <!-- intentionallySkip -->
  <testcase classname="testngTestcases.Testcase2" name="assertFalseCond">
    <skipped/>
  </testcase> <!-- assertFalseCond -->
  <system-out>
    <![CDATA[Test has been started: userReg
Test has been passed: userReg
Test has been started: login
Login Test
Test has been passed: login
Test has been finished: Testcase1
Test has been started: assertTrueCond
Verifying titles
Test has been failed: assertTrueCond
<a href="C:\Users\Bhagya_Kudupudi\Desktop\download.png" target="_blank">screenshot</a>
<a href="C:\Users\Bhagya_Kudupudi\Desktop\download.png" target="_blank"><img src="C:\Users\Bhagya_Kudupudi\Desktop\download.png" height=200 width=200</a>
Test has been started: intentionallyFail
Intentionally Failing Test
Test has been failed: intentionallyFail
<a href="C:\Users\Bhagya_Kudupudi\Desktop\download.png" target="_blank">screenshot</a>
<a href="C:\Users\Bhagya_Kudupudi\Desktop\download.png" target="_blank"><img src="C:\Users\Bhagya_Kudupudi\Desktop\download.png" height=200 width=200</a>
Test has been started: intentionallySkip
Test has been started: softAssertCond
Test has been failed: softAssertCond
<a href="C:\Users\Bhagya_Kudupudi\Desktop\download.png" target="_blank">screenshot</a>
<a href="C:\Users\Bhagya_Kudupudi\Desktop\download.png" target="_blank"><img src="C:\Users\Bhagya_Kudupudi\Desktop\download.png" height=200 width=200</a>
Test has been started: verifyTitle
Test has been failed: verifyTitle
<a href="C:\Users\Bhagya_Kudupudi\Desktop\download.png" target="_blank">screenshot</a>
<a href="C:\Users\Bhagya_Kudupudi\Desktop\download.png" target="_blank"><img src="C:\Users\Bhagya_Kudupudi\Desktop\download.png" height=200 width=200</a>]]>
  </system-out>
</testsuite> <!-- testngTestcases.Testcase2 -->
